Workspace crud
mickotomic/StandUp pull request #13
Opened 2023-06-05 19:45 UTC by miroslavrs81

2023-06-05 20:28 UTC, stefanj122 commented on src/app/workspace/workspace.service.ts
> +    return this.workspaceRepository.save(workspace);
Here you probably want to await this save method and why return type is't Promise<Workspace>?

2023-06-05 20:34 UTC, stefanj122 commented on src/app/workspace/workspace.service.ts
> +    if ( workspace.deletedAt === null ) {
This condition will be true if workspace is't deleted, you probably want to check if deletedAt is not null.

2023-06-05 20:44 UTC, stefanj122 commented on src/app/workspace/workspace.service.ts
> +    return await this.workspaceRepository.update(id, updateWorkspaceDto);
Only owner of the workspace can update and delete workspace and return from update method won't give any useful information to FE.

2023-06-06 16:34 UTC, Branimir requested changes

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.controller.ts
> +  @Get()
This should be filtered by the current user

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.controller.ts
> +  ): Promise<Workspace> {
This should be filtered by the current user as well

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.controller.ts
> +    return await this.workspaceService.updateWorkspace(+id, updateWorkspaceDto);
This action should be possible only if the current user is owner

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.controller.ts
> +    @GetUser() user: User) {
This action should be possible only if the current user is owner

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.controller.ts
> +    @GetUser() user: User ) {
This action should be possible only if the current user is owner

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.service.ts
> +  async findAllWorkspaces(): Promise<Workspace[]> {
Filter by current user

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.service.ts
> +  async removeWorkspace(id: number) {
Check if owner

2023-06-06 16:34 UTC, Branimir commented on src/app/workspace/workspace.service.ts
> +  async restoreWorkspace(id: number) {
Check if owner

2023-06-06 17:29 UTC, miroslavrs81 commented on src/app/workspace/workspace.service.ts
> +    // const workspace = this.workspaceRepository.create(createWorkspaceDto);
ownerId should be just owner

2023-06-22 19:49 UTC, Branimir approved these changes

2023-06-22 20:38 UTC, merged